include "config.do"

include "bootstrap_se_for_dynamic_Tables_8_9.do"
include "bootstraped_se_for_static_Tables_7_8_9.do"
include "Figure_2_prices_exices_tax_Rosstat.do"
include "Figure_A2_share_samogon.do"
include "Figures_3_7_graphs_around_kink.do"
include "Table_10_survival_regressions.do"
include "Table_11_test_for_kink_in_other_vars.do"
include "Table_A1.do"
include "Table_A3.do"
include "Table_A4_dynamic_model_hazarddeath_discounting.do"
include "Table_A5a_IV_robustness.do"
include "Table_A5b_diff_measures_alco_robustness.do"
include "Table_A5c_regional_level_regressions.do"
include "Table_A5d_reduced_form_RKD.do"
include "Table_OA6_habits_vs_unoberved_heterogeneity.do"
include "Tables_1_2.do"
//data confidential for tables 3 and 4, so this do file is not included
do "Tables_5_OA2_OA3_survival_diff_causes.do"
do "Tables_7_9_static_model.do"
do "Tables_8_9_6_Dynamic_and_all_IV.do"

cd "${basepath}/Replication_files/Figures_456OA1_simulations"
include "get_coefficients_for_simulations.do"
include "hermits.do"
include "simulation_Figure4_no_peers.do"
include "simulation_Figures4_5_6_OA1.do"
